return {
	["Standard"] = {
		Index = 1,
		["GroupA"] = "None",
		["GroupB"] = "None"
	},
	["Female"] = {
		Index = 2,
		["GroupA"] = "Medium",
		["GroupB"] = "None"
	},
	["Male"] = {
		Index = 3,
		["GroupA"] = "None",
		["GroupB"] = "Medium - Human A"
	},
	["Intersex"] = {
		Index= 4,
		["GroupA"] = "Medium",
		["GroupB"] = "Medium - Human A"
	},
	["Small Female"] = {
		Index = 5,
		["GroupA"] = "Small",
		["GroupB"] = "None"
	},
	["Small Male"] = {
		Index = 6,
		["GroupA"] = "None",
		["GroupB"] = "Small - Human A"
	},
	["Small Intersex"] = {
		Index= 7,
		["GroupA"] = "Small",
		["GroupB"] = "Small - Human A"
	},
}
